language: scala
sudo: false
dist: xenial
jdk: openjdk8
scala:
  - 2.12.8
script: sbt test
notifications:
  email: false
  slack:
    secure: "qGjlbQR3iRW9mOReKQbOGOGlqTsmDnBYFK1J4zuOhU5DZlD6Yh+sNgYDFLTm+Lo3o2Jbe4fo8rM8bv0jVcW58Yj32MIWnKTBLQPEq2fTj8nQTm6T7wGDYt6qy4Mhi6ARxwJCLZUNikl8XYbcClFWmsNChoqOq/BH4OZ2/XDNbhhbR5ofQOgrJf/joFviXf9quxdIn1IHC/j6u2lC5XVcY5wWhDDASLBPjc4hHDGs5zItH66kveirSZQmtCEXvw5r/hg8BJlFtSmhQu5khxztSH6iVqiQ4PHacel6iyVoQpfYZpKS7lXyFW0egQgI7vD5R4V9+EgtdG/2XB4JCXjGBNVU2fLovxUekcsii5giqOgY1bgr1z019fnQQxgnWG8wSZgGgPHMqUev7Tv8WoT2oVFVQdzuNUONIdzayQUlcwI9CYkDxE0uWvHNNI60TlsP/nboDZRYEub/XpZSW7XgLSwOoIAQjn/1rzoNdMSTshEvP4thxE3QZODIuGRNOFECSpxF9SElgph0Op0zL/wld3JuScHHJfs8OtzkuX8xn7rbz43zCOg/wWk0bZgiux90HdpRrPncaEXtuKHwVMhC6mfGEhvOA5RP2kJg+WrHTlz+wtyft7b/c3C8TOEgoKUk6Hyk8/5yku2ljmQgSu7LWVswJcl874wLJC9gGQNc1KQ="
