version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - restore_cache:
          key: sbtcache
      - run: sbt ++2.12.11! check
      - save_cache:
          key: sbtcache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test212_jdk8:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - restore_cache:
          key: sbtcache
      - run: sbt ++2.12.11! akka-sample/compile circe-sample/test cop/test dashboard/test finch-sample/compile gcpclient/compile gof/compile grammar/compile http4s-sample/compile sip/compile socket/compile zio/compile
      - save_cache:
          key: sbtcache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test213_jdk11:
    docker:
      - image: circleci/openjdk:11-jdk-node
    steps:
      - checkout
      - restore_cache:
          key: sbtcache
      - run: sbt ++2.13.2! akka-sample/compile circe-sample/test cop/test dashboard/test finch-sample/compile gcpclient/compile gof/compile grammar/compile http4s-sample/compile sip/compile socket/compile zio/compile
      - save_cache:
          key: sbtcache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

#  release:
#    docker:
#      - image: circleci/openjdk:8-jdk-node
#    steps:
#      - checkout
#      - run: git fetch --tags
#      - restore_cache:
#          key: sbtcache
#      - run: echo "credentials += Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", \"$SONATYPE_USER\", \"$SONATYPE_PASSWORD\")" > ~/.sbt/1.0/sonatype.sbt
#      - run: echo -n "${PGP_PUBLIC}" | base64 -d > /tmp/public.asc
#      - run: echo -n "${PGP_SECRET}" | base64 -d > /tmp/secret.asc
#      - run: sbt ++${SCALA_VERSION}! clean sonatypeBundleClean +publishSigned sonatypeBundleRelease

workflows:
  version: 2
  build:
    jobs:
      - lint:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - test212_jdk8:
          requires:
            - lint
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - test213_jdk11:
          requires:
            - lint
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
#      - release:
#          context: Sonatype
#          requires:
#            - test212_jdk8
#            - test213_jdk11
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only: /^v[0-9]+(\.[0-9]+)*$/
#      - microsite:
#          filters:
#            branches:
#              only:
#                - master
